### ISSUE TITLE
About the co-occurrence loss

### ISSUE THREAD

**Issue by yw155** [twke18/SPML#2]
Hi, thanks for sharing your great work in advance. I would like to ask a question that how to represent the relationship of co-occurrence and how to compute it. Could you provide a more detailed explanation? Thank you.

**Comment by twke18** [comment]
Ideawise, we capture the co-occurrence relationship among two images by finding the object categories occurred in both images. In our implementation, we keep track of all the occurring object categories of an image as a NUM_CLASSES-dimension binary vector, where value 1 indicates the occurrence of corresponding object category and vice versa. You can check `targets['semantic_tags']` (e.g [here](https://github.com/twke18/SPML/blob/1bacae8963176489cda465e8e9b1f5b7384ace57/spml/models/predictions/segsort_softmax.py#L146-L148)). Note: we do not take `background` class into accounts.

To decide if two images share any object categories, we just need to dot product the corresponding image-tag vectors. If the final value is larger than 1, then we know there's at least one object category appears in both images. Otherwise, these two images do not share any occurring object category.

You can see [this function](https://github.com/twke18/SPML/blob/1bacae8963176489cda465e8e9b1f5b7384ace57/spml/utils/segsort/loss.py#L85-L130) to get a sense of how to formulate segsort loss w.r.t image tags.
